-- DHB-29 / Phase 2 §1 + §14.1 migration 002: all enum types (additive only)

CREATE TYPE "org_kind" AS ENUM ('PERSONAL', 'TEAM');
CREATE TYPE "org_role" AS ENUM ('OWNER', 'ADMIN', 'MEMBER', 'BILLING');
CREATE TYPE "project_role" AS ENUM ('OWNER', 'ADMIN', 'EDITOR', 'VIEWER');
CREATE TYPE "upload_session_status" AS ENUM ('issued', 'uploaded', 'consumed', 'expired', 'failed');
CREATE TYPE "document_status" AS ENUM ('queued', 'processing', 'completed', 'failed', 'partial', 'cancelled', 'stale');
CREATE TYPE "document_block_type" AS ENUM ('heading', 'paragraph', 'list', 'table_row', 'table_cell', 'figure', 'caption', 'equation', 'reference');
CREATE TYPE "embedding_status" AS ENUM ('pending', 'ok', 'failed');
CREATE TYPE "source_type" AS ENUM ('document', 'external_record');
CREATE TYPE "evidence_stance" AS ENUM ('supports', 'contradicts', 'neutral', 'unresolved');
CREATE TYPE "evidence_type" AS ENUM ('body_grounded', 'metadata_only');
CREATE TYPE "extraction_method" AS ENUM ('deterministic', 'llm', 'human');
CREATE TYPE "ai_capability" AS ENUM ('EMBED', 'CHAT', 'RERANK', 'AUTOCOMPLETE', 'EXTRACT_CELL', 'SCREENING', 'STANCE', 'SYNTHESIS', 'OCR');
CREATE TYPE "ai_status" AS ENUM ('pending', 'ok', 'failed');
CREATE TYPE "ai_method" AS ENUM ('llm', 'deterministic');
CREATE TYPE "research_run_preset" AS ENUM ('deep_research', 'extraction_matrix', 'chat', 'custom');
CREATE TYPE "research_run_state" AS ENUM ('CREATED', 'PLANNING', 'RUNNING', 'PAUSED_BUDGET', 'PAUSED_MANUAL', 'COMPLETING', 'COMPLETED', 'COMPLETED_PARTIAL', 'FAILED', 'CANCELLED');
CREATE TYPE "research_step_state" AS ENUM ('PENDING', 'READY', 'DISPATCHED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'DEFERRED', 'CANCELLED');
CREATE TYPE "extraction_run_state" AS ENUM ('pending', 'running', 'completed', 'completed_partial', 'failed', 'cancelled');
CREATE TYPE "extraction_cell_status" AS ENUM ('pending', 'running', 'ok', 'failed', 'skipped');
CREATE TYPE "screening_decision_kind" AS ENUM ('include', 'exclude', 'unresolved');
CREATE TYPE "canonical_work_type" AS ENUM ('article', 'preprint', 'chapter', 'book');
CREATE TYPE "identifier_scheme" AS ENUM ('doi', 'pmid', 'arxiv', 'isbn', 's2_id');
CREATE TYPE "work_relationship_type" AS ENUM ('is_preprint_of', 'is_journal_version_of', 'is_erratum_to', 'is_correction_of', 'is_retracted_by', 'retracts', 'is_translation_of', 'cites', 'cited_by');
CREATE TYPE "merge_match_type" AS ENUM ('exact_doi', 'corroborated_pmid_arxiv', 'fuzzy_title');
CREATE TYPE "merge_status" AS ENUM ('pending', 'merged', 'rejected');
CREATE TYPE "external_record_type" AS ENUM ('web_page', 'zotero_item');
CREATE TYPE "discovery_status" AS ENUM ('pending_admission', 'admitted', 'rejected', 'expired');
CREATE TYPE "stripe_event_status" AS ENUM ('received', 'processed', 'processing_failed');
CREATE TYPE "usage_metric" AS ENUM ('ai_tokens', 'ai_cost_micros', 'documents', 'storage_bytes', 'seats');
CREATE TYPE "actor_type" AS ENUM ('user', 'system', 'service');
CREATE TYPE "research_artifact_type" AS ENUM ('extraction_matrix', 'deep_research_report', 'synthesis', 'consensus');
CREATE TYPE "extraction_column_type" AS ENUM ('TEXT', 'LONG_TEXT', 'NUMBER', 'BOOLEAN', 'DATE', 'ENUM', 'MULTI_ENUM', 'RANGE', 'ENTITY', 'CITATION');
CREATE TYPE "import_session_state" AS ENUM ('CREATED', 'PARSING', 'ADMITTING', 'COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED');
CREATE TYPE "message_role" AS ENUM ('user', 'assistant', 'system');
CREATE TYPE "message_status" AS ENUM ('pending', 'streaming', 'complete', 'failed', 'cancelled');
CREATE TYPE "writing_status" AS ENUM ('draft', 'in_review', 'final', 'archived');
CREATE TYPE "writing_type" AS ENUM ('manuscript', 'review', 'protocol', 'note');
CREATE TYPE "auth_token_purpose" AS ENUM ('email_verification', 'password_reset');
